//
//  UserProfileModels.swift
//  Whalether
//
//  Created by Natthaaek on 15/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserProfileModel {
    // MARK: Use cases
    
    enum Profile {
        struct Response {
            var email: String
            var displayName: String
        }
        struct ViewModel {
            var email: String
            var displayName: String
        }
    }
    
    enum ChangeDisplayName {
        struct Request {
            var displayName: String
        }
    }
    
}
